homeserver:
  url: http://localhost:8008
  domain: localhost

verto:
  url: "ws://fs.yourdomain:8081/"
  passwd: "some password"
  
verto-dialog-params:
  useVideo: true
  useStereo: true
  screenShare: false
  useCamera: "any"
  useMic: "any"
  tag: "webcam"
  localTag: null
  login: "1008@fs.yourdomain"
  destination_number: "3500"
  caller_id_name: "FreeSWITCH User"
  caller_id_number: "1008"
  outgoingBandwidth: "default"
  incomingBandwidth: "default"
  dedEnc: false
  mirrorInput: false
  remote_caller_id_name: "Outbound Call"
  remote_caller_id_number: "3500"
