type: object
required: ["homeserver"]
properties:
  homeserver:
    type: object
    properties:
      url:
        type: string
      domain:
        type: string
    additionalProperties: false
    required: ["url", "domain"]
  verto:
    type: object
    properties:
      url:
        type: string
      passwd:
        type: string
    additionalProperties: false
    required: ["url", "passwd"]
  verto-dialog-params:
    type: object
    properties:
      useVideo:
        type: boolean
      useStereo:
        type: boolean
      tag:
        type: string
      login:
        type: string
      destination_number:
        type: string
      caller_id_name:
        type: string
      caller_id_number:
        type: string
      callID:
        type: string
      remote_caller_id_name:
        type: string
      remote_caller_id_number:
        type: string