
on:
  push:
    tags: ["testing-[0-9].[0-9].[0-9]"]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changelog
        id: extract-changelog
        run: |
          git fetch --tags --force
          RELEASE_BODY=`git diff --minimal --no-color HEAD~ CHANGELOG.md | tail -n +6 | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | head -n -3`
          RELEASE_NAME="${{ github.ref_name }} $(date +'%Y-%m-%d')"
          RELEASE_BODY=`git tag -l --format='%(contents:body)' ${{ github.ref_name }}`
          echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_OUTPUT
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     name: ${{ steps.extract-changelog.outputs.RELEASE_NAME }}
      #     body: ${{ steps.extract-changelog.outputs.RELEASE_BODY }}
      #     draft: true # Draft it
      #     token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token